---
- name: Install nginx on server
  hosts: all
  become: yes
  tasks:
#    - name: Update apt cache
#      apt:
#        update_cache: yes
#      - name: Install nginx on all server
#      apt:
#        name: nginx
#        state: latest
#

    - name: prit a ip adress
      debug:
        var: "ansible_all_ipv4_addresses"

    - name: prit boot image
      debug:
        var: "ansible_cmdline.BOOT_IMAGE"

    - name: execute shell command
      shell: echo "hello world"
      register: shell_output

    - name: Display the output
      debug:
        msg: "the output of command is: {{ shell_output }}"

    - name: Check if file exists
      shell: hostname -I
      register: file_check

    - name: print file exist massage
      debug:
        msg: "file exist"
      when: file_check.rc == 0

    - name: print file does not exist
      debug:
        msg: "file does not exist"
      when: file_check.rc != 0

    - name: install package on Debian base system
      apt:
       name: "{{ item }}"
       state: present
      loop:
        - vim
        - git
        - sl
        - curl
        - htop
        - nlod
      when: ansible_facts['os_family'] == "Debian"

    - name: install package on Debian base system
      apt:
       name: ["vim", "git", "sl", "htop"]
       state: present
      when: ansible_facts['os_family'] == "Debian"


    - name: install package on Redhat  base system
      yum:
        name: vim
        state: present
      when: ansible_facts['os_family'] == "RedHat"

######## Copy
    - name: copy file from local to servers
      copy:
        src: /home/file1.txt
        dest: /opt/ansible_file1.txt
        owner: meisam
        group: root
        mode: '0777'

######## service
    - name: Restart nginx service
      service:
        name: nginx
        state: restarted
        enabled: yes
